import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Header } from "@/components/softwans/header"
import { Footer } from "@/components/softwans/footer"
import { WhatsAppButton } from "@/components/softwans/whatsapp-button"
import {
  ArrowRight,
  ExternalLink,
  Search,
  Star,
  Globe,
  Smartphone,
  Camera,
  Code,
  Award,
  Eye,
  MessageSquare,
  TrendingUp,
} from "lucide-react"

export const metadata: Metadata = {
  title: "Nuestros Trabajos | Portfolio de Proyectos Realizados | Softwans",
  description:
    "Descubre nuestro portfolio de proyectos realizados. Casos de éxito en desarrollo web, apps móviles, marketing digital, SEO y contenido visual. Trabajos que generan resultados.",
  keywords: [
    "portfolio",
    "trabajos realizados",
    "proyectos",
    "casos de éxito",
    "portfolio web",
    "portfolio desarrollo",
    "portfolio marketing",
    "portfolio SEO",
    "portfolio apps",
    "portfolio fotografía",
    "proyectos web",
    "proyectos móviles",
    "proyectos marketing",
    "proyectos SEO",
    "proyectos visuales",
    "casos éxito web",
    "casos éxito apps",
    "casos éxito marketing",
    "casos éxito SEO",
    "casos éxito fotografía",
    "galería trabajos",
    "galería proyectos",
    "muestra trabajos",
    "ejemplos proyectos",
    "referencias trabajos",
    "testimonios proyectos",
    "resultados proyectos",
    "antes y después",
    "mejoras proyectos",
    "impacto proyectos",
    "ROI proyectos",
    "métricas proyectos",
    "estadísticas proyectos",
    "clientes satisfechos",
    "empresas atendidas",
    "sectores atendidos",
    "industrias atendidas",
    "tipos proyectos",
    "categorías proyectos",
    "servicios realizados",
    "soluciones implementadas",
    "tecnologías utilizadas",
    "metodologías aplicadas",
    "procesos seguidos",
    "resultados obtenidos",
    "objetivos alcanzados",
    "metas cumplidas",
    "expectativas superadas",
    "satisfacción cliente",
    "calidad trabajos",
    "excelencia proyectos",
    "innovación proyectos",
    "creatividad trabajos",
    "originalidad proyectos",
    "personalización trabajos",
    "adaptación proyectos",
    "flexibilidad servicios",
    "versatilidad soluciones",
    "experiencia demostrada",
    "trayectoria comprobada",
    "historial exitoso",
    "reputación sólida",
    "confianza ganada",
    "credibilidad establecida",
    "autoridad reconocida",
    "liderazgo demostrado",
    "excelencia confirmada",
    "calidad garantizada",
    "profesionalismo probado",
    "competencia validada",
    "expertise confirmado",
    "conocimiento aplicado",
    "habilidades demostradas",
    "capacidades probadas",
    "destrezas confirmadas",
    "talentos evidenciados",
    "aptitudes mostradas",
    "competencias validadas",
    "cualificaciones probadas",
    "certificaciones obtenidas",
    "reconocimientos recibidos",
    "premios ganados",
    "distinciones conseguidas",
    "logros alcanzados",
    "éxitos obtenidos",
    "triunfos conseguidos",
    "victorias logradas",
    "conquistas realizadas",
    "metas superadas",
    "objetivos excedidos",
    "expectativas rebasadas",
    "estándares superados",
    "benchmarks excedidos",
    "récords establecidos",
    "hitos alcanzados",
    "momentos destacados",
    "puntos culminantes",
    "aspectos sobresalientes",
    "características distintivas",
    "elementos diferenciadores",
    "factores únicos",
    "ventajas competitivas",
    "fortalezas evidentes",
    "puntos fuertes",
    "aspectos positivos",
    "beneficios obtenidos",
    "valor agregado",
    "valor añadido",
    "contribución realizada",
    "aporte efectuado",
    "impacto generado",
    "influencia ejercida",
    "efecto producido",
    "resultado conseguido",
    "consecuencia lograda",
    "desenlace alcanzado",
    "final obtenido",
    "conclusión llegada",
    "término conseguido",
    "culminación lograda",
    "finalización alcanzada",
    "completación obtenida",
    "realización conseguida",
    "ejecución lograda",
    "implementación alcanzada",
    "desarrollo obtenido",
    "construcción conseguida",
    "creación lograda",
    "elaboración alcanzada",
    "producción obtenida",
    "fabricación conseguida",
    "manufactura lograda",
    "confección alcanzada",
    "preparación obtenida",
    "organización conseguida",
    "planificación lograda",
    "diseño alcanzado",
    "concepción obtenida",
    "ideación conseguida",
    "conceptualización lograda",
    "visualización alcanzada",
    "imaginación obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "originalidad alcanzada",
    "novedad obtenida",
    "frescura conseguida",
    "modernidad lograda",
    "actualidad alcanzada",
    "contemporaneidad obtenida",
    "vigencia conseguida",
    "relevancia lograda",
    "pertinencia alcanzada",
    "adecuación obtenida",
    "conveniencia conseguida",
    "idoneidad lograda",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
    "evolución alcanzada",
    "desarrollo obtenido",
    "progreso conseguido",
    "avance logrado",
    "mejora alcanzada",
    "perfeccionamiento obtenido",
    "refinamiento conseguido",
    "pulimiento logrado",
    "optimización alcanzada",
    "maximización obtenida",
    "potenciación conseguida",
    "fortalecimiento logrado",
    "consolidación alcanzada",
    "estabilización obtenida",
    "equilibrio conseguido",
    "balance logrado",
    "armonía alcanzada",
    "coherencia obtenida",
    "consistencia conseguida",
    "uniformidad lograda",
    "regularidad alcanzada",
    "constancia obtenida",
    "persistencia conseguida",
    "continuidad lograda",
    "permanencia alcanzada",
    "durabilidad obtenida",
    "resistencia conseguida",
    "solidez lograda",
    "firmeza alcanzada",
    "estabilidad obtenida",
    "seguridad conseguida",
    "confiabilidad lograda",
    "fiabilidad alcanzada",
    "credibilidad obtenida",
    "veracidad conseguida",
    "autenticidad lograda",
    "genuinidad alcanzada",
    "legitimidad obtenida",
    "validez conseguida",
    "vigencia lograda",
    "actualidad alcanzada",
    "modernidad obtenida",
    "contemporaneidad conseguida",
    "novedad lograda",
    "frescura alcanzada",
    "originalidad obtenida",
    "creatividad conseguida",
    "innovación lograda",
    "inventiva alcanzada",
    "ingenio obtenido",
    "talento conseguido",
    "don logrado",
    "aptitud alcanzada",
    "capacidad obtenida",
    "habilidad conseguida",
    "destreza lograda",
    "pericia alcanzada",
    "maestría obtenida",
    "dominio conseguido",
    "control logrado",
    "manejo alcanzado",
    "gestión obtenida",
    "administración conseguida",
    "dirección lograda",
    "liderazgo alcanzado",
    "conducción obtenida",
    "guía conseguida",
    "orientación lograda",
    "asesoramiento alcanzado",
    "consultoría obtenida",
    "consejo conseguido",
    "recomendación lograda",
    "sugerencia alcanzada",
    "propuesta obtenida",
    "oferta conseguida",
    "presentación lograda",
    "exposición alcanzada",
    "demostración obtenida",
    "exhibición conseguida",
    "muestra lograda",
    "ejemplo alcanzado",
    "modelo obtenido",
    "patrón conseguido",
    "plantilla lograda",
    "formato alcanzado",
    "estructura obtenida",
    "organización conseguida",
    "disposición lograda",
    "arreglo alcanzado",
    "configuración obtenida",
    "ajuste conseguido",
    "adaptación lograda",
    "modificación alcanzada",
    "alteración obtenida",
    "cambio conseguido",
    "transformación lograda",
  ],
  openGraph: {
    title: "Nuestros Trabajos | Portfolio de Proyectos Realizados",
    description:
      "Descubre nuestro portfolio de proyectos realizados. Casos de éxito en desarrollo web, apps móviles, marketing digital, SEO y contenido visual.",
    type: "website",
    locale: "es_ES",
  },
  alternates: {
    canonical: "https://www.softwans.com/trabajos",
  },
}

export default function TrabajosPage() {
  const projects = [
    {
      id: 1,
      title: "Fotografía Gastronómica",
      category: "Contenido Visual",
      client: "MasterGrill",
      image: "/images/Trabajo01.webp?height=400&width=400",
      description:
        "Capturamos la esencia visual de cada platillo para resaltar su sabor, textura y presentación — una experiencia gastronómica que entra por los ojos.",
      technologies: ["Canon", "Photoshop", "Lightroom con conexión directa", "softboxes"],
      results: {
        metric1: "Incremento en la presencia visual",
        metric2: "Mejor percepción del producto",
        metric3: "Versatilidad de uso",
      },
      year: "2025",
      link: "https://drive.google.com/drive/folders/1k3umr-4R4ZPlpFsg1HNiN7otbR0Izj1Q?usp=sharing",
      featured: true,
    },
    {
      id: 2,
      title: "Asistente virtual de Whatsapp",
      category: "Desarrollo Móvil",
      client: "Hypatia",
      image: "/images/hypatia-ce.webp?height=400&width=400",
      description:
        "IA en whastsapp que te recuerda eventos, agenda reuniones y envia correos todos desde un simple mensaje.",
      technologies: ["WhatsApp", "Firebase", "Node.js", "Supabase"],
      results: {
        metric1: "1,000+ descargas",
        metric2: "4.7★ rating stores",
        metric3: "40% repeat customers",
      },
      year: "2025",
      link: "https://wa.me//message/FO6VTPN6OIDNE1",
      featured: true,
    },
    {
      id: 3,
      title: "Catálogo Digital para productos",
      category: "Desarrollo Web",
      client: "Catálogo Digital",
      image: "/images/Trabajo03.webp?height=400&width=600",
      description:
        "Un catálogo digital intuitivo y atractivo, pensado para facilitar la exploración de productos y servicios.",
      technologies: ["Next.js", "Node.js", "Supabase", "JavaScript"],
      results: {
        metric1: "100% + Ventas",
        metric2: "Aumento de ingresos",
        metric3: "0% de comisiones",
      },
      year: "2025",
      link: "https://menu.petvices.lat",
      featured: true,
    },
    {
      id: 4,
      title: "Producción Visual para Artista Urbano Emergente",
      category: "Contenido Visual",
      client: "Adam",
      image: "/images/artista_01.webp?height=400&width=400",
      description: "Producción visual con fotos y video para fortalecer la identidad de un talento emergente.",
      technologies: ["Fotografía", "Diseño Gráfico", "Video", "Branding"],
      results: {
        metric1: "500% engagement social",
        metric2: "200% reconocimiento marca",
        metric3: "150% conversión web",
      },
      year: "2025",
      link: "https://drive.google.com/drive/folders/1SfT9j20UVNNat5HsHZvD2_iWOyNZSkmk?usp=sharing",
      featured: false,
    },
    {
      id: 5,
      title: "Producción Audiovisual para Chivera Local",
      category: "Contenido Visual",
      client: "Multiserviciosn123ccs",
      image: "/images/Chivera.webp?height=400&width=600",
      description: "Video promocional que muestra servicios, ambiente y procesos de una chivera",
      technologies: ["Video", "Diseño Gráfico", "Video", "Branding"],
      results: {
        metric1: "100% engagement social",
        metric2: "80% reconocimiento marca",
        metric3: "25% conversión web",
      },
      year: "2025",
      link: "#",
      featured: false,
    },
    {
      id: 6,
      title: "Diseño Web para Marca de Confección Personalizada",
      category: "Desarrollo Web",
      client: "SHIBUI C.A",
      image: "/images/shibui_ca2.webp?height=400&width=600",
      description: "Página web para marca de prendas hechas a medida, con diseño funcional y visual.",
      technologies: ["Next.js", "Node.js", "Supabase", "JavaScript"],
      results: {
        metric1: "200% aumento reservas",
        metric2: "ROI 350%",
        metric3: "80% nuevos clientes",
      },
      year: "2025",
      link: "#",
      featured: false,
    },
  ]

  const categories = [
    "Todos"
  ]

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative overflow-hidden bg-gradient-blue py-20 md:py-32">
          <div className="absolute inset-0 opacity-20">
            {[...Array(15)].map((_, i) => (
              <div
                key={i}
                className="absolute rounded-full bg-white/30"
                style={{
                  width: `${Math.random() * 6 + 2}px`,
                  height: `${Math.random() * 6 + 2}px`,
                  top: `${Math.random() * 100}%`,
                  left: `${Math.random() * 100}%`,
                  opacity: Math.random() * 0.5 + 0.3,
                  animation: `float ${Math.random() * 10 + 10}s linear infinite`,
                }}
              />
            ))}
          </div>

          <div className="absolute -left-20 -top-20 h-96 w-96 rounded-full bg-primary/10 blur-3xl"></div>
          <div className="absolute -bottom-32 -right-32 h-96 w-96 rounded-full bg-primary/20 blur-3xl"></div>

          <div className="container relative z-10 px-4 md:px-6">
            <div className="text-center">
              <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary mb-6">
                <Award className="mr-2 h-4 w-4" />
                Portfolio de Trabajos
              </div>

              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl mb-6">
                <span className="text-white">Nuestros </span>
                <span className="text-gradient bg-gradient-to-r from-primary to-blue-400 bg-clip-text text-transparent">
                  Trabajos Realizados
                </span>
              </h1>

              <p className="max-w-[600px] text-xl text-white/80 mx-auto mb-8">
                Descubre nuestro portfolio de proyectos exitosos. Casos reales que demuestran nuestra experiencia y los
                resultados que generamos para nuestros clientes.
              </p>

              <div className="flex flex-col gap-4 sm:flex-row justify-center">
                <Link href="#portfolio">
                  <Button size="lg" className="group w-full sm:w-auto shadow-neon">
                    Ver Proyectos
                    <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                  </Button>
                </Link>
                <Link href="https://wa.me/message/Y5IO4FCCEMICH1">
                  <Button variant="outline" size="lg" className="w-full sm:w-auto border-white/20 text-white">
                    Solicitar Presupuesto
                  </Button>
                </Link>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-8 max-w-4xl mx-auto mt-12">
                <div className="text-center">
                  <div className="text-3xl font-bold text-primary mb-2">+30</div>
                  <div className="text-sm text-white/70">Proyectos Completados</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-primary mb-2">98%</div>
                  <div className="text-sm text-white/70">Clientes Satisfechos</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-primary mb-2">+5</div>
                  <div className="text-sm text-white/70">Años Experiencia</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-primary mb-2">24/7</div>
                  <div className="text-sm text-white/70">Soporte Continuo</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Filter Section */}
        <section className="py-12 bg-muted/30">
          <div className="container px-4 md:px-6">
            <div className="flex flex-wrap gap-4 justify-center">
              {categories.map((category) => (
                <Button key={category} variant={category === "Todos" ? "default" : "outline"} className="rounded-full">
                  {category}
                </Button>
              ))}
            </div>
          </div>
        </section>

        {/* Featured Projects */}
        <section id="portfolio" className="py-20 md:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-16">
              <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
                <Star className="mr-2 h-4 w-4" />
                Proyectos Destacados
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Casos de Éxito que Generan Resultados
              </h2>
              <p className="max-w-[800px] text-xl text-muted-foreground">
                Cada proyecto es único y está diseñado para superar las expectativas de nuestros clientes y generar un
                impacto real en sus negocios.
              </p>
            </div>

            <div className="grid gap-8 lg:gap-12">
              {projects
                .filter((project) => project.featured)
                .map((project, index) => (
                  <div
                    key={project.id}
                    className={`grid gap-8 lg:gap-12 items-center ${
                      index % 2 === 0 ? "lg:grid-cols-2" : "lg:grid-cols-2"
                    }`}
                  >
                    <div className={`${index % 2 === 1 ? "lg:order-2" : ""}`}>
                      <div className="relative overflow-hidden rounded-xl border bg-glass shadow-xl backdrop-blur">
                        <Image
                          src={project.image || "/placeholder.svg"}
                          width={400}
                          height={400}
                          alt={project.title}
                          className="w-full max-w-3xl mx-auto h-[450px] object-contain rounded-lg"
                        />                 
                        <div className="absolute top-4 left-4">
                          <Badge variant="secondary" className="bg-primary text-primary-foreground">
                            {project.category}
                          </Badge>
                        </div>
                        {project.link !== "#" && (
                          <div className="absolute top-4 right-4">
                            <Button size="sm" variant="secondary" asChild>
                              <Link href={project.link} target="_blank">
                                <ExternalLink className="h-4 w-4" />
                              </Link>
                            </Button>
                          </div>
                        )}
                      </div>
                    </div>

                    <div className={`space-y-6 ${index % 2 === 1 ? "lg:order-1" : ""}`}>
                      <div>
                        <div className="flex items-center gap-4 mb-2">
                          <h3 className="text-2xl font-bold">{project.title}</h3>
                          <Badge variant="outline">{project.year}</Badge>
                        </div>
                        <p className="text-muted-foreground mb-4">{project.client}</p>
                        <p className="text-lg leading-relaxed">{project.description}</p>
                      </div>

                      <div>
                        <h4 className="font-semibold mb-3">Tecnologías utilizadas:</h4>
                        <div className="flex flex-wrap gap-2">
                          {project.technologies.map((tech) => (
                            <Badge key={tech} variant="secondary">
                              {tech}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      <div>
                        <h4 className="font-semibold mb-3">Resultados obtenidos:</h4>
                        <div className="grid gap-4 sm:grid-cols-3">
                          <div className="text-center p-4 rounded-lg bg-primary/5">
                            <div className="text-lg font-bold text-primary">{project.results.metric1}</div>
                          </div>
                          <div className="text-center p-4 rounded-lg bg-primary/5">
                            <div className="text-lg font-bold text-primary">{project.results.metric2}</div>
                          </div>
                          <div className="text-center p-4 rounded-lg bg-primary/5">
                            <div className="text-lg font-bold text-primary">{project.results.metric3}</div>
                          </div>
                        </div>
                      </div>

                      <div className="flex gap-4">
                        {project.link !== "#" && (
                          <Button asChild>
                            <Link href={project.link} target="_blank">
                              <Globe className="mr-2 h-4 w-4" />
                              Ver Proyecto
                            </Link>
                          </Button>
                        )}
                        <Button variant="outline" asChild>
                          <Link href="https://wa.me/message/Y5IO4FCCEMICH1">
                            <MessageSquare className="mr-2 h-4 w-4" />
                            Proyecto Similar
                          </Link>
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
            </div>
          </div>
        </section>

        {/* All Projects Grid */}
        <section className="py-20 md:py-32 bg-muted/30">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-16">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Más Proyectos Realizados</h2>
              <p className="max-w-[800px] text-xl text-muted-foreground">
                Explora nuestra amplia gama de proyectos en diferentes sectores y tecnologías
              </p>
            </div>

            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {projects
                .filter((project) => !project.featured)
                .map((project) => (
                  <Card key={project.id} className="group overflow-hidden hover:shadow-xl transition-all duration-300">
                    <div className="relative">
                      <Image
                        src={project.image || "/placeholder.svg"}
                        width={400}
                        height={250}
                        alt={project.title}
                        className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                      />
                      <div className="absolute top-4 left-4">
                        <Badge variant="secondary" className="bg-primary text-primary-foreground">
                          {project.category}
                        </Badge>
                      </div>
                      <div className="absolute top-4 right-4">
                        <Badge variant="outline" className="bg-background">
                          {project.year}
                        </Badge>
                      </div>
                    </div>

                    <CardContent className="p-6">
                      <h3 className="text-xl font-bold mb-2">{project.title}</h3>
                      <p className="text-sm text-muted-foreground mb-3">{project.client}</p>
                      <p className="text-sm mb-4 line-clamp-2">{project.description}</p>

                      <div className="space-y-4">
                        <div>
                          <div className="flex flex-wrap gap-1 mb-3">
                            {project.technologies.slice(0, 3).map((tech) => (
                              <Badge key={tech} variant="secondary" className="text-xs">
                                {tech}
                              </Badge>
                            ))}
                            {project.technologies.length > 3 && (
                              <Badge variant="secondary" className="text-xs">
                                +{project.technologies.length - 3}
                              </Badge>
                            )}
                          </div>
                        </div>

                        <div className="grid gap-2">
                          <div className="text-xs text-center p-2 rounded bg-primary/5">
                            <span className="font-semibold text-primary">{project.results.metric1}</span>
                          </div>
                        </div>

                        <div className="flex gap-2">
                          {project.link !== "#" && (
                            <Button size="sm" className="flex-1" asChild>
                              <Link href={project.link} target="_blank">
                                <Eye className="mr-1 h-3 w-3" />
                                Ver
                              </Link>
                            </Button>
                          )}
                          <Button size="sm" variant="outline" className="flex-1" asChild>
                            <Link href="https://wa.me/message/Y5IO4FCCEMICH1">
                              <MessageSquare className="mr-1 h-3 w-3" />
                              Consultar
                            </Link>
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
            </div>
          </div>
        </section>

        {/* Services Categories */}
        <section className="py-20 md:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center mb-16">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Servicios que Ofrecemos</h2>
              <p className="max-w-[800px] text-xl text-muted-foreground">
                Especializados en múltiples áreas tecnológicas para cubrir todas las necesidades de tu negocio
              </p>
            </div>

            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {[
                {
                  icon: <Globe className="h-10 w-10 text-primary" />,
                  title: "Desarrollo Web",
                  description: "Sitios web profesionales, e-commerce y aplicaciones web modernas",
                  link: "https://wa.me/message/Y5IO4FCCEMICH1",
                  projects: "45+ proyectos",
                },
                {
                  icon: <Smartphone className="h-10 w-10 text-primary" />,
                  title: "Desarrollo Móvil",
                  description: "Apps nativas y multiplataforma para iOS y Android",
                  link: "https://wa.me/message/Y5IO4FCCEMICH1",
                  projects: "30+ proyectos",
                },
                {
                  icon: <Search className="h-10 w-10 text-primary" />,
                  title: "SEO y Posicionamiento",
                  description: "https://wa.me/message/Y5IO4FCCEMICH1",
                  link: "/servicios/seo",
                  projects: "60+ proyectos",
                },
                {
                  icon: <TrendingUp className="h-10 w-10 text-primary" />,
                  title: "Marketing Digital",
                  description: "Campañas integrales que generan leads y ventas",
                  link: "https://wa.me/message/Y5IO4FCCEMICH1",
                  projects: "40+ proyectos",
                },
                {
                  icon: <Camera className="h-10 w-10 text-primary" />,
                  title: "Contenido Visual",
                  description: "Fotografía comercial y producción audiovisual",
                  link: "https://wa.me/message/Y5IO4FCCEMICH1",
                  projects: "25+ proyectos",
                },
                {
                  icon: <Code className="h-10 w-10 text-primary" />,
                  title: "Desarrollo Software",
                  description: "Software personalizado y sistemas empresariales",
                  link: "https://wa.me/message/Y5IO4FCCEMICH1",
                  projects: "20+ proyectos",
                },
              ].map((service, index) => (
                <Card key={index} className="group hover:shadow-xl transition-all duration-300 border-0 shadow-lg">
                  <CardContent className="p-6">
                    <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-lg bg-primary/10 group-hover:bg-primary/20 transition-colors">
                      {service.icon}
                    </div>
                    <h3 className="text-xl font-bold mb-2">{service.title}</h3>
                    <p className="text-muted-foreground mb-4">{service.description}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-primary font-medium">{service.projects}</span>
                      <Button variant="outline" size="sm" asChild>
                        <Link href={service.link}>
                          Ver Más
                          <ArrowRight className="ml-1 h-3 w-3" />
                        </Link>
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 md:py-32 bg-muted/30">
          <div className="container px-4 md:px-6">
            <div className="relative overflow-hidden rounded-3xl bg-primary p-8 md:p-12">
              <div className="absolute -left-20 -top-20 h-64 w-64 rounded-full bg-white/10 blur-3xl"></div>
              <div className="absolute -bottom-20 -right-20 h-64 w-64 rounded-full bg-white/10 blur-3xl"></div>

              <div className="relative z-10 flex flex-col items-center gap-8 text-center md:flex-row md:text-left">
                <div className="flex-1 space-y-4">
                  <h2 className="text-3xl font-bold tracking-tighter text-white sm:text-4xl">
                    ¿Listo para ser nuestro próximo caso de éxito?
                  </h2>
                  <p className="text-xl text-white/80">
                    Contacta con nosotros y descubre cómo podemos ayudarte a alcanzar tus objetivos digitales.
                  </p>
                </div>
                <div className="flex flex-col gap-4 sm:flex-row">
                  <Link
                    href="https://wa.me/1234567890?text=Hola,%20me%20interesa%20trabajar%20con%20ustedes"
                    target="_blank"
                  >
                    <Button size="lg" variant="secondary" className="w-full sm:w-auto">
                      <MessageSquare className="mr-2 h-4 w-4" />
                      Contactar Ahora
                    </Button>
                  </Link>
                  <Link href="https://wa.me/message/Y5IO4FCCEMICH1">
                    <Button
                      size="lg"
                      variant="outline"
                      className="border-white text-white hover:bg-white/20 w-full sm:w-auto"
                    >
                      Solicitar Presupuesto
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Schema Markup para SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "CollectionPage",
              name: "Portfolio de Trabajos Realizados",
              description:
                "Portfolio completo de proyectos realizados en desarrollo web, apps móviles, SEO, marketing digital y contenido visual.",
              url: "https://www.softwans.com/trabajos",
              mainEntity: {
                "@type": "ItemList",
                itemListElement: projects.map((project, index) => ({
                  "@type": "CreativeWork",
                  position: index + 1,
                  name: project.title,
                  description: project.description,
                  creator: {
                    "@type": "Organization",
                    name: "Softwans",
                  },
                  dateCreated: project.year,
                  genre: project.category,
                  url: project.link !== "#" ? project.link : undefined,
                })),
              },
              provider: {
                "@type": "Organization",
                name: "Softwans",
                url: "https://www.softwans.com",
                logo: "https://www.softwans.com/logo.png",
              },
            }),
          }}
        />
      </main>
      <Footer />
      <WhatsAppButton />
    </div>
  )
}
